# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/Capstone/ip_repo/MappingLayer/src/zcu102.xdc

# IP: d:/Capstone/ip_repo/MappingLayer/src/dsp_macro_0/dsp_macro_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# IP: d:/Capstone/ip_repo/MappingLayer/src/dsp_Requant/dsp_Requant.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_Requant || ORIG_REF_NAME==dsp_Requant} -quiet] -quiet

# IP: d:/Capstone/ip_repo/MappingLayer/src/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: d:/Capstone/ip_repo/MappingLayer/src/line_buffer/line_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==line_buffer || ORIG_REF_NAME==line_buffer} -quiet] -quiet

# XDC: d:/capstone/ip_repo/mappinglayer/tmp_edit_project.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/capstone/ip_repo/mappinglayer/tmp_edit_project.gen/sources_1/ip/line_buffer/line_buffer_ooc.xdc
