# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/josuh/Desktop/Projects/Capstone/Y_Converter_19.1/Y_Converter_19.1.cache/wt [current_project]
set_property parent.project_path C:/Users/josuh/Desktop/Projects/Capstone/Y_Converter_19.1/Y_Converter_19.1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/josuh/Desktop/Projects/Capstone/Y_Converter_19.1/Y_Converter_19.1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/josuh/Desktop/Projects/Capstone/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/imports/Desktop/yconv_pipelined_multiplier_2stage.v
  C:/Users/josuh/Desktop/Projects/Capstone/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/imports/Desktop/Y_Converter.v
}
read_ip -quiet c:/Users/josuh/Desktop/Projects/Capstone/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xci
set_property used_in_implementation false [get_files -all c:/Users/josuh/Desktop/Projects/Capstone/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/josuh/Desktop/Projects/Capstone/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Y_Converter -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Y_Converter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Y_Converter_utilization_synth.rpt -pb Y_Converter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
