# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Capstone/BicubicDDRTest/BicubicDDRTest.srcs/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_axi_dma_0_1/BicubicDDRTest_axi_dma_0_1.xci
# IP: The module: 'BicubicDDRTest_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_axi_dma_0_1/BicubicDDRTest_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_axi_dma_0_1/BicubicDDRTest_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_axi_dma_0_1/BicubicDDRTest_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Capstone/BicubicDDRTest/BicubicDDRTest.srcs/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_axi_dma_0_1/BicubicDDRTest_axi_dma_0_1.xci
# IP: The module: 'BicubicDDRTest_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_axi_dma_0_1/BicubicDDRTest_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_axi_dma_0_1/BicubicDDRTest_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_axi_dma_0_1/BicubicDDRTest_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
