set_property SRC_FILE_INFO {cfile:{D:/Capstone/Bicubic Resizer/Bicubic Resizer.srcs/constrs_1/new/constraints.xdc} rfile:{../../../../Bicubic Resizer/Bicubic Resizer.srcs/constrs_1/new/constraints.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name ref_clk [get_ports i_clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN [get_nets i_clk]
