# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/emergency/FSRCNN_imple2.vol1/ip_repo/AXI4S_Feature_Extraction_Layer/AXI4S_Feature_Extraction_Layer.srcs/sources_1/ip/feature_fifo_generator_0/feature_fifo_generator_0.xci
# IP: The module: 'feature_fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/emergency/FSRCNN_imple2.vol1/ip_repo/AXI4S_Feature_Extraction_Layer/AXI4S_Feature_Extraction_Layer.gen/sources_1/ip/feature_fifo_generator_0/feature_fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'feature_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/emergency/FSRCNN_imple2.vol1/ip_repo/AXI4S_Feature_Extraction_Layer/AXI4S_Feature_Extraction_Layer.gen/sources_1/ip/feature_fifo_generator_0/feature_fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'feature_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/emergency/FSRCNN_imple2.vol1/ip_repo/AXI4S_Feature_Extraction_Layer/AXI4S_Feature_Extraction_Layer.srcs/sources_1/ip/feature_fifo_generator_0/feature_fifo_generator_0.xci
# IP: The module: 'feature_fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/emergency/FSRCNN_imple2.vol1/ip_repo/AXI4S_Feature_Extraction_Layer/AXI4S_Feature_Extraction_Layer.gen/sources_1/ip/feature_fifo_generator_0/feature_fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'feature_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/emergency/FSRCNN_imple2.vol1/ip_repo/AXI4S_Feature_Extraction_Layer/AXI4S_Feature_Extraction_Layer.gen/sources_1/ip/feature_fifo_generator_0/feature_fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'feature_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
