# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FSRCNN_imple2/ip_repo/AXIS_Y_Converter_v19.1_0910/AXIS_Y_Converter_v19.1_0910.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xci
# IP: The module: 'yconv_fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FSRCNN_imple2/ip_repo/AXIS_Y_Converter_v19.1_0910/AXIS_Y_Converter_v19.1_0910.gen/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'yconv_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FSRCNN_imple2/ip_repo/AXIS_Y_Converter_v19.1_0910/AXIS_Y_Converter_v19.1_0910.gen/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'yconv_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FSRCNN_imple2/ip_repo/AXIS_Y_Converter_v19.1_0910/AXIS_Y_Converter_v19.1_0910.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xci
# IP: The module: 'yconv_fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FSRCNN_imple2/ip_repo/AXIS_Y_Converter_v19.1_0910/AXIS_Y_Converter_v19.1_0910.gen/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'yconv_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FSRCNN_imple2/ip_repo/AXIS_Y_Converter_v19.1_0910/AXIS_Y_Converter_v19.1_0910.gen/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'yconv_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
