# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Capstone/Bicubic Resizer/Bicubic Resizer.srcs/constrs_1/new/constraints.xdc

# Block Designs: bd/BicubicDDRTest/BicubicDDRTest.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BicubicDDRTest || ORIG_REF_NAME==BicubicDDRTest} -quiet] -quiet

# IP: bd/BicubicDDRTest/ip/BicubicDDRTest_BicubicResizer_0_0/BicubicDDRTest_BicubicResizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BicubicDDRTest_BicubicResizer_0_0 || ORIG_REF_NAME==BicubicDDRTest_BicubicResizer_0_0} -quiet] -quiet

# IP: bd/BicubicDDRTest/ip/BicubicDDRTest_zynq_ultra_ps_e_0_0/BicubicDDRTest_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BicubicDDRTest_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==BicubicDDRTest_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/BicubicDDRTest/ip/BicubicDDRTest_axi_dma_0_1/BicubicDDRTest_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BicubicDDRTest_axi_dma_0_1 || ORIG_REF_NAME==BicubicDDRTest_axi_dma_0_1} -quiet] -quiet

# IP: bd/BicubicDDRTest/ip/BicubicDDRTest_ps8_0_axi_periph_1/BicubicDDRTest_ps8_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BicubicDDRTest_ps8_0_axi_periph_1 || ORIG_REF_NAME==BicubicDDRTest_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/BicubicDDRTest/ip/BicubicDDRTest_rst_ps8_0_99M_0/BicubicDDRTest_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BicubicDDRTest_rst_ps8_0_99M_0 || ORIG_REF_NAME==BicubicDDRTest_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/BicubicDDRTest/ip/BicubicDDRTest_axi_smc_1/BicubicDDRTest_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BicubicDDRTest_axi_smc_1 || ORIG_REF_NAME==BicubicDDRTest_axi_smc_1} -quiet] -quiet

# IP: bd/BicubicDDRTest/ip/BicubicDDRTest_system_ila_0_2/BicubicDDRTest_system_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BicubicDDRTest_system_ila_0_2 || ORIG_REF_NAME==BicubicDDRTest_system_ila_0_2} -quiet] -quiet

# IP: bd/BicubicDDRTest/ip/BicubicDDRTest_auto_pc_0/BicubicDDRTest_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BicubicDDRTest_auto_pc_0 || ORIG_REF_NAME==BicubicDDRTest_auto_pc_0} -quiet] -quiet

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/BicubicDDRTest_ooc.xdc
