# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FSRCNN_imple2/ip_repo/AXIS_Shrinking_Layer_v19.1_0910/AXIS_Shrinking_Layer_v19.1_0910.srcs/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1.xci
# IP: The module: 'shrink_fifo_generator_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FSRCNN_imple2/ip_repo/AXIS_Shrinking_Layer_v19.1_0910/AXIS_Shrinking_Layer_v19.1_0910.gen/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'shrink_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FSRCNN_imple2/ip_repo/AXIS_Shrinking_Layer_v19.1_0910/AXIS_Shrinking_Layer_v19.1_0910.gen/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shrink_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/FSRCNN_imple2/ip_repo/AXIS_Shrinking_Layer_v19.1_0910/AXIS_Shrinking_Layer_v19.1_0910.srcs/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1.xci
# IP: The module: 'shrink_fifo_generator_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FSRCNN_imple2/ip_repo/AXIS_Shrinking_Layer_v19.1_0910/AXIS_Shrinking_Layer_v19.1_0910.gen/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'shrink_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FSRCNN_imple2/ip_repo/AXIS_Shrinking_Layer_v19.1_0910/AXIS_Shrinking_Layer_v19.1_0910.gen/sources_1/ip/shrink_fifo_generator_1/shrink_fifo_generator_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shrink_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
