# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jungh/vivado_jungho/DECONV_renamed/DECONV_renamed.srcs/sources_1/ip/deconv_fifo_generator_1/deconv_fifo_generator_1.xci
# IP: The module: 'deconv_fifo_generator_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jungh/vivado_jungho/DECONV_renamed/DECONV_renamed.gen/sources_1/ip/deconv_fifo_generator_1/deconv_fifo_generator_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'deconv_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jungh/vivado_jungho/DECONV_renamed/DECONV_renamed.gen/sources_1/ip/deconv_fifo_generator_1/deconv_fifo_generator_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'deconv_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/jungh/vivado_jungho/DECONV_renamed/DECONV_renamed.srcs/sources_1/ip/deconv_fifo_generator_1/deconv_fifo_generator_1.xci
# IP: The module: 'deconv_fifo_generator_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jungh/vivado_jungho/DECONV_renamed/DECONV_renamed.gen/sources_1/ip/deconv_fifo_generator_1/deconv_fifo_generator_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'deconv_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jungh/vivado_jungho/DECONV_renamed/DECONV_renamed.gen/sources_1/ip/deconv_fifo_generator_1/deconv_fifo_generator_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'deconv_fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
