# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Capstone/BicubicDDRTest/BicubicDDRTest.srcs/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_zynq_ultra_ps_e_0_0/BicubicDDRTest_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'BicubicDDRTest_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_zynq_ultra_ps_e_0_0/BicubicDDRTest_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_zynq_ultra_ps_e_0_0/BicubicDDRTest_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Capstone/BicubicDDRTest/BicubicDDRTest.srcs/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_zynq_ultra_ps_e_0_0/BicubicDDRTest_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'BicubicDDRTest_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_zynq_ultra_ps_e_0_0/BicubicDDRTest_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Capstone/BicubicDDRTest/BicubicDDRTest.gen/sources_1/bd/BicubicDDRTest/ip/BicubicDDRTest_zynq_ultra_ps_e_0_0/BicubicDDRTest_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BicubicDDRTest_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
