# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/shrink_fifo_generator_1/shrink_fifo_generator_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shrink_fifo_generator_1 || ORIG_REF_NAME==shrink_fifo_generator_1} -quiet] -quiet

# IP: ip/shrink_dsp48_macro_1/shrink_dsp48_macro_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shrink_dsp48_macro_1 || ORIG_REF_NAME==shrink_dsp48_macro_1} -quiet] -quiet
