# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FSRCNN/ip_repo/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xci
# IP: The module: 'yconv_fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FSRCNN/ip_repo/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'yconv_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FSRCNN/ip_repo/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'yconv_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/FSRCNN/ip_repo/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xci
# IP: The module: 'yconv_fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FSRCNN/ip_repo/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'yconv_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FSRCNN/ip_repo/Y_Converter_19.1/Y_Converter_19.1.srcs/sources_1/ip/yconv_fifo_generator_0/yconv_fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'yconv_fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
