# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mapping_layer/mapping_layer.srcs/sources_1/ip/dsp_Requant/dsp_Requant.xci
# IP: The module: 'dsp_Requant' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mapping_layer/mapping_layer.gen/sources_1/ip/dsp_Requant/dsp_Requant_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_Requant'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/mapping_layer/mapping_layer.srcs/sources_1/ip/dsp_Requant/dsp_Requant.xci
# IP: The module: 'dsp_Requant' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mapping_layer/mapping_layer.gen/sources_1/ip/dsp_Requant/dsp_Requant_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_Requant'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
